name: Test Workflow Trigger

on:
  push:
    paths:
      - '**'   # Trigger on any file change - very open trigger for testing

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Confirm trigger
        run: echo "GitHub Actions workflow triggered successfully on push!"
