/* ========== PDF/PRINT STYLES ========== */

/* Page setup for A4 printing */
@page {
    size: A4;
    margin: 10mm;
}

/* Print-specific styles */
@media print {
    /* Hide the PDF button when printing */
    .pdf-button-container {
        display: none !important;
    }
    
    * {
        -webkit-print-color-adjust: exact !important;
        color-adjust: exact !important;
        print-color-adjust: exact !important;
    }
    
    body {
        background: white !important;
        padding: 0 !important;
        font-size: 10pt !important;
        line-height: 1.3 !important;
    }
    
    .container {
        max-width: none !important;
        width: 100% !important;
        margin: 0 !important;
        padding: 0 !important;
        box-shadow: none !important;
        border-radius: 0 !important;
        background: white !important;
    }
    
    .header {
        margin-bottom: 8px !important;
        padding-bottom: 8px !important;
    }
    
    .header h1 {
        font-size: 18pt !important;
        margin-bottom: 3px !important;
        line-height: 1.1 !important;
    }
    
    .header h2 {
        font-size: 12pt !important;
        margin-bottom: 6px !important;
        line-height: 1.2 !important;
    }
    
    .contact-info {
        text-align: center !important;
        margin-top: 6px !important;
        line-height: 1.2 !important;
        white-space: nowrap !important;
    }
    
    .contact-item {
        display: inline-block !important;
        margin: 0 8px !important;
        font-size: 8pt !important;
        line-height: 1.2 !important;
        white-space: nowrap !important;
        vertical-align: middle !important;
    }
    
    .contact-item a {
        font-size: 8pt !important;
        line-height: 1.2 !important;
        white-space: nowrap !important;
    }
    
    .section {
        margin-bottom: 8px !important;
        page-break-inside: avoid !important;
    }
    
    .section-title {
        font-size: 11pt !important;
        margin-bottom: 6px !important;
        padding-bottom: 2px !important;
        line-height: 1.2 !important;
    }
    
    /* SKILLS GRID FOR PRINT */
    .skills-grid {
        display: grid !important;
        grid-template-columns: repeat(4, 1fr) !important;
        gap: 4px 3px !important;
        padding: 6px 0 !important;
        page-break-inside: avoid !important;
    }
    
    .skill-item {
        display: flex !important;
        align-items: center !important;
        gap: 4px !important;
        padding: 2px 1px !important;
        border: none !important;
        background: none !important;
        page-break-inside: avoid !important;
    }
    
    .skill-item img {
        width: 14px !important;
        height: 14px !important;
        object-fit: contain !important;
        flex-shrink: 0 !important;
    }
    
    .skill-item span {
        font-size: 7pt !important;
        line-height: 1.1 !important;
        font-weight: 500 !important;
    }
    
    .experience-item {
        margin-bottom: 8px !important;
        padding: 6px !important;
        background-color: #f8f9fa !important;
        border-radius: 2px !important;
        page-break-inside: avoid !important;
    }
    
    /* Awards Container for Print */
    .awards-container {
        padding: 6px !important;
        margin-bottom: 8px !important;
        background-color: #f8f9fa !important;
        border-radius: 2px !important;
        page-break-inside: avoid !important;
    }
    
    .job-header {
        position: relative !important;
        margin-bottom: 6px !important;
        width: 100% !important;
        min-height: 20px !important;
    }
    
    .job-header > div:first-child {
        position: absolute !important;
        left: 0 !important;
        top: 0 !important;
        width: 70% !important;
    }
    
    .job-title {
        font-size: 10pt !important;
        line-height: 1.1 !important;
        margin: 0 !important;
    }
    
    .company {
        font-size: 8pt !important;
        line-height: 1.2 !important;
        margin-top: 2px !important;
    }
    
    .duration {
        position: absolute !important;
        right: 0 !important;
        top: 0 !important;
        font-size: 7pt !important;
        line-height: 1.1 !important;
        text-align: right !important;
        width: 28% !important;
        margin: 0 !important;
        padding: 0 !important;
        white-space: nowrap !important;
    }
    
    .achievements {
        line-height: 1.4 !important;
    }
    
    .achievements li {
        margin-bottom: 2px !important;
        font-size: 7pt !important;
        padding-left: 8px !important;
        line-height: 1.4 !important;
        text-align: justify !important;
        text-justify: inter-word !important;
    }
    
    .awards-list {
        margin-bottom: 6px !important;
        line-height: 1.4 !important;
    }
    
    .awards-list li {
        margin-bottom: 2px !important;
        font-size: 7pt !important;
        padding-left: 8px !important;
        line-height: 1.4 !important;
        text-align: justify !important;
        text-justify: inter-word !important;
    }
    
    .education-item {
        padding: 4px 8px !important;
        margin-bottom: 4px !important;
        background-color: #f8f9fa !important;
        border-radius: 2px !important;
        page-break-inside: avoid !important;
    }
    
    .degree {
        font-size: 9pt !important;
        line-height: 1.2 !important;
    }
    
    .institution {
        font-size: 8pt !important;
        margin: 1px 0 !important;
        line-height: 1.2 !important;
    }
    
    .education-details {
        font-size: 7pt !important;
        line-height: 1.2 !important;
        display: flex !important;
        justify-content: space-between !important;
    }
    
    /* FORCE PAGE BREAK AFTER ANALYST TO SEPARATE SECTIONS */
    .experience-item:nth-of-type(2) {
        page-break-after: always !important;
    }
    
    /* Prevent orphans */
    .experience-item,
    .education-item,
    .awards-container {
        page-break-inside: avoid !important;
    }
}
