- name: Install Puppeteer
  run: npm install puppeteer@20.7.4

- name: Generate PDF
  run: |
    node -e "
    const puppeteer = require('puppeteer');
    const fs = require('fs');

    (async () => {
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });

      const page = await browser.newPage();

      // Read the HTML file
      const html = fs.readFileSync('./index.html', 'utf8');

      await page.setContent(html, { waitUntil: 'networkidle0' });

      // Wait extra for any resources to load
      await page.waitForTimeout(2000);

      // Generate PDF with print media type
      await page.pdf({
        path: 'Krishna-Resume.pdf',
        format: 'A4',
        margin: { top: '15mm', right: '15mm', bottom: '15mm', left: '15mm' },
        printBackground: true,
        preferCSSPageSize: true
      });

      await browser.close();
      console.log('PDF generated successfully!');
    })();
    "
